export default {
  signIn: 'sign in',
  signUp: 'sign up',
  name: 'name',
  password: 'password',
  hasSignIn: 'has sign in',
  hasSignUp: 'has sign up',
  keepMe: 'Keep Me Signed In',
  playerName: 'Player\'s name',
  gameProgress: 'game progress',
  start: 'start',
  credits: 'credits',
  attendanceOverYear: 'Game attendance over the year',
  statistics: 'Statistics',
  profile: 'Profile',
  overallRating: 'Overall rating',
  achievements: 'achievements',
  youGot: 'You got',
  achievementsOutOf: 'achievements out of',
  all: 'all',
  ourTeam: 'Our team',
  gratitude: 'Gratitude',
  specialThanksFrom: 'Special thanks from',
  myTeam: 'my team',
  per: 'per',
  andEndurance: 'and endurance!',
  andPeopleFromChats: 'and people from chats',
  myTurtle: 'my turtle',
  forStressReliefAndBuoyancy: 'for stress relief and buoyancy',
  forMentoringAndStrongShoulder: 'for a mentoring and strong shoulder',
  forJokesCommunicationAndHelp: 'for jokes, communication and help',
  forEverythingAndEvenMore: 'for everything and even more',
  achievs: {
    firstBlood: 'First Blood',
    firstAsterisk: 'First Asterisk',
    seller: 'Seller',
    killer: 'Killer',
    builder: 'Builder',
    ironDefender: 'Iron Defender',
    greatDefender: 'Great Defender',
    completeWin: 'Complete Win',
  },
  loading: 'Loading',
  level: 'level',
  easy: 'easy',
  normal: 'normal',
  hard: 'hard',
  towersNumber: 'Possible towers number',
  wave: 'wave',
  options: 'options',
  music: 'Music',
  sound: 'Sound',
  failed: 'failed',
  sorry: 'SORRY :(/LEVEL FAILED',
  win: 'you win!',
  congrats: 'CONGRATULATIONS!/LEVEL COMPLETE',
  slow: 'slow',
  medium: 'medium',
  fast: 'fast',
  small: 'small',
  long: 'long',
  levelTheme: {
    1: 'Greeting, noble and heroic warrior! As a General of His Mejesty\'s forces, King Denas requires your services. A band of Orcs approaches near the capital! Theay are beasts who only think about looting and burning everything in their wake. It is necessary to stop these crimes before they grow from troubles to problems. ',
    2: 'General, the orc gang was not our biggest problem! The inhabitants of the city of Southport have reported attacks by Black Wizards from the Forbidden Lands. You must take a batalion to Southport to bolster the city\' defenses. Good luck, General!',
    3: 'Defender of Linerea! We are at the gates of ancient Hammerhold. Hordes of Black Mages, Orcs and Scorpions are overrunning the few troops still defenfing the fortress wall. Time is of the essence general, we must rush to their aid!',
  },
  enemy: {
    littleOrc: 'little orc',
    wizardBlack: 'wizard black',
    scorpio: 'scorpio',
    levendor: 'Levendor',
  },
  tower: {
    archers: 'ARCHERS TOWER',
    artillery: 'ARTILLERY TOWER',
    magic: 'MAGIC TOWER',
  },
  hotkeysTitle: 'Hot Keys',
  hotkeys: [
    { key: 'CTRL+Q', info: 'quit game from levels page' },
    { key: 'KEY NUMBERS', info: 'choose appropriate level' },
    { key: 'KEY D', info: 'change the game difficulty' },
    { key: 'ENTER', info: 'start game(when choosing level)' },
    { key: 'CTRL+M', info: 'go to levels page(when game is paused)' },
    { key: 'ESC', info: 'close modal' },
    { key: 'KEY N', info: 'start first wave' },
    { key: 'CTRL+SPACE', info: 'pause the game' },
    { key: 'CTRL+LEFT/RIGHT', info: 'appropriate button when win/lose' },
  ],
  price: 'price',
  damage: 'damage',
};
