export default {
  signIn: 'sign in',
  signUp: 'sign up',
  name: 'name',
  password: 'password',
  keepMe: 'Keep Me Signed In',
  playerName: 'Player\'s name',
  gameProgress: 'game progress',
  start: 'start',
  credits: 'credits',
  attendanceOverYear: 'Game attendance over the year',
  statistics: 'Statistics',
  profile: 'Profile',
  overallRating: 'Overall rating',
  achievements: 'achievements',
  achievs: {
    firstBlood: 'First Blood',
    firstAsterisk: 'First Asterisk',
    seller: 'Seller',
    killer: 'Killer',
    builder: 'Builder',
    ironDefender: 'Iron Defender',
    greatDefender: 'Great Defender',
    completeWin: 'Complete Win',
  },
  loading: 'Loading',
  level: 'level',
  easy: 'easy',
  normal: 'normal',
  hard: 'hard',
  towersNumber: 'Possible towers number',
  wave: 'wave',
  options: 'options',
  music: 'Music',
  sound: 'Sound',
  failed: 'failed',
  sorry: 'SORRY :(/LEVEL FAILED',
  win: 'you win!',
  congrats: 'CONGRATULATIONS!/LEVEL COMPLETE',
  verySlow: 'very slow',
  slow: 'slow',
  medium: 'medium',
  fast: 'fast',
  veryFast: 'very fast',
  small: 'small',
  long: 'long',
  levelTheme: {
    1: 'This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english.',
    2: 'This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english.',
    3: 'This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english.',
  },
  enemy: {
    littleOrc: 'little orc',
    wizardBlack: 'wizard black',
    scorpio: 'scorpio'
  },
  tower: {
    archers: 'ARCHERS TOWER',
    artillery: 'ARTILLERY TOWER',
    magic: 'MAGIC TOWER'
  }
}
