export default {
  start: 'start',
  credits: 'credits',
  attendanceOverYear: 'Game attendance over the year',
  profile: 'Profile',
  overallRating: 'Overall rating',
  achievements: 'achievements',
  loading: 'Loading',
  level: 'level',
  easy: 'easy',
  normal: 'normal',
  hard: 'hard',
  towersNumber: 'Possible towers number',
  wave: 'wave',
  options: 'options',
  music: 'music',
  sound: 'sound',
  failed: 'failed',
  sorry: 'SORRY :(/LEVEL FAILED',
  win: 'you win!',
  congrats: 'CONGRATULATIONS!/LEVEL COMPLETE',
  verySlow: 'very slow',
  slow: 'slow',
  medium: 'medium',
  fast: 'fast',
  small: 'small',
  long: 'long',
  levelTheme: {
    1: 'This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english.',
    2: 'This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english.',
    3: 'This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english. This text is in english.',
  },
}
