export default {
  signIn: 'kirish',
  signUp: 'ro\'yxatdan o\'tish',
  name: 'ism',
  password: 'parol',
  keepMe: 'Meni eslab qolish',
  playerName: 'O\'yinchining ismi',
  gameProgress: 'o\'yin rivojlanishi',
  start: 'boshlash',
  credits: 'mualliflar',
  attendanceOverYear: 'Yillik tashriflar soni',
  statistics: 'Statistika',
  profile: 'Profil',
  overallRating: 'Umumiy reyting',
  achievements: 'yutuqlar',
  achievs: {
    firstBlood: 'Birinchi Qon',
    firstAsterisk: 'Birinchi Yulduz',
    seller: 'Sotuvchi',
    killer: 'Qotil',
    builder: 'Quruvchi',
    ironDefender: 'Kuchli Himoyachi',
    greatDefender: 'Ajoyib Himoyachi',
    completeWin: 'To\'liq G\'alaba',
  },
  loading: 'Yuklanmoqda',
  level: 'bosqich',
  easy: 'oson',
  normal: 'oddiy',
  hard: 'qiyin',
  towersNumber: 'Minoralar uchun joylar soni',
  wave: 'to\'lqin',
  options: 'sozlamalar',
  music: 'Musiqa',
  sound: 'Tovush',
  failed: 'mag\'lubiyat',
  sorry: 'UZUR :(/MUVAFFAQIYATSIZ/YAKUN',
  win: 'g\'alaba!',
  congrats: 'TABRIKLAR!/MUVAFFAQIYATLI/YAKUN',
  verySlow: 'juda sekin',
  slow: 'sekin',
  medium: 'o\'rtacha',
  fast: 'tez',
  veryFast: 'juda tez',
  small: 'kichik',
  long: 'uzoq',
  levelTheme: {
    1: 'Sizga salom beraman va sizning olijanobligingiz va jasoratingiz oldida bosh egaman! Ulug\'vor podshoh Denas o\'z generalini xizmatga chaqiradi. Poytaxt yaqinida orklar to\'dasi ko\'rindi! Bu jonzotlar faqat o\'z yo\'llaridagi hamma narsani talon-taroj qilishni va yoqishni biladilar. Ushbu jinoyatlar o\'sishdan oldin ularni to\'xtatish kerak.',
    2: 'General, orklar to\'dasi bizning eng katta muammoimiz emas bo\'lib chiqdi! Janubiy port aholisi Taqiqlangan Yerlardan Qora Sehrgarlar tomonidan qilingan hujumlar haqida xabar berishdi. Siz va sizning batalyoningiz shahar xavfsizligini ta\'minlash uchun u yerga safarbar qilindingiz. Omad tilaymiz, general!',
    3: 'Lineriya himoyachisi, biz qadimgi Hammerhold darvozasi oldidamiz. Qora Sehrgarlar, Orklar va Chayonlar qo\'shinlari qal\'a devorlarining so\'nggi himoyachilarini tez orada yo\'q qiladilar. Bunga aralashish va do\'stlaringizga yordam qo\'lini cho\'zish vaqti keldi!',
  },
  enemy: {
    littleOrc: 'kichik ork',
    wizardBlack: 'qora sehrgar',
    scorpio: 'chayon'
  },
  tower: {
    archers: 'KAMONCHILAR MINORASI',
    artillery: 'ARTILLERYA MINORASI',
    magic: 'SEHRGAR MINORASI'
  },
  price: 'narx',
  damage: 'zarar',
}
