export default {
  signIn: 'kirish',
  signUp: 'ro`yxatdan o`tish',
  name: 'ism',
  password: 'parol',
  keepMe: 'Meni eslab qolish',
  playerName: 'O`yinchining ismi',
  gameProgress: 'o`yin rivojlanishi',
  start: 'boshlash',
  credits: 'mualliflar',
  attendanceOverYear: 'Yillik tashriflar soni',
  statistics: 'Statistika',
  profile: 'Profil',
  overallRating: 'Umumiy reyting',
  achievements: 'yutuqlar',
  achievs: {
    firstBlood: 'Birinchi Qon',
    firstAsterisk: 'Birinchi Yulduz',
    seller: 'Sotuvchi',
    killer: 'Qotil',
    builder: 'Quruvchi',
    ironDefender: 'Kuchli Himoyachi',
    greatDefender: 'Ajoyib Himoyachi',
    completeWin: 'To`liq G`alaba',
  },
  loading: 'Yuklanmoqda',
  level: 'bosqich',
  easy: 'oson',
  normal: 'oddiy',
  hard: 'qiyin',
  towersNumber: 'Minoralar uchun joylar soni',
  wave: 'to`lqin',
  options: 'sozlamalar',
  music: 'Musiqa',
  sound: 'Tovush',
  failed: 'mag`lubiyat',
  sorry: 'UZUR :(/MUVAFFAQIYATSIZ/YAKUN',
  win: 'g`alaba!',
  congrats: 'TABRIKLAR!/MUVAFFAQIYATLI/YAKUN',
  verySlow: 'juda sekin',
  slow: 'sekin',
  medium: 'o`rtacha',
  fast: 'tez',
  veryFast: 'juda tez',
  small: 'kichik',
  long: 'uzoq',
  levelTheme: {
    1: 'O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn.',
    2: 'O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn.',
    3: 'O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn. O`zbekcha matn.',
  },
  enemy: {
    littleOrc: 'kichik ork',
    wizardBlack: 'qora sehrgar',
    scorpio: 'chayon'
  },
  tower: {
    archers: 'KAMONCHILAR MINORASI',
    artillery: 'ARTILLERYA MINORASI',
    magic: 'SEHRGAR MINORASI'
  }
}
