export default {
  signIn: 'kirish',
  signUp: 'ro`yxatdan o`tish',
  name: 'ism',
  password: 'parol',
  keepMe: 'Meni eslab qolish',
  playerName: 'O`yinchining ismi',
  gameProgress: 'o`yin rivojlanishi',
  start: 'boshlash',
  credits: 'mualliflar',
  attendanceOverYear: 'Yillik tashriflar soni',
  statistics: 'Statistika',
  profile: 'Profil',
  overallRating: 'Umumiy reyting',
  achievements: 'yutuqlar',
  achievs: {
    firstBlood: 'Birinchi Qon',
    firstAsterisk: 'Birinchi Yulduz',
    seller: 'Sotuvchi',
    killer: 'Qotil',
    builder: 'Quruvchi',
    ironDefender: 'Kuchli Himoyachi',
    greatDefender: 'Ajoyib Himoyachi',
    completeWin: 'To`liq G`alaba',
  },
  loading: 'Yuklanmoqda',
  level: 'bosqich',
  easy: 'oson',
  normal: 'oddiy',
  hard: 'qiyin',
  towersNumber: 'Minoralar uchun joylar soni',
  wave: 'to`lqin',
  options: 'sozlamalar',
  music: 'Musiqa',
  sound: 'Tovush',
  failed: 'mag`lubiyat',
  sorry: 'UZUR :(/MUVAFFAQIYATSIZ/YAKUN',
  win: 'g`alaba!',
  congrats: 'TABRIKLAR!/MUVAFFAQIYATLI/YAKUN',
  verySlow: 'juda sekin',
  slow: 'sekin',
  medium: 'o`rtacha',
  fast: 'tez',
  veryFast: 'juda tez',
  small: 'kichik',
  long: 'uzoq',
  levelTheme: {
    1: 'Men sizga salom beraman va sizning olijanobligingiz va jasoratingiz oldida bosh egaman! Ulug\'vor podshoh Denas o\'z generalini xizmatga chaqiradi. Poytaxt yaqinida orklar to\'dasi ko\'rindi! Bu jonzotlar faqat o\'z yo\'llarida hamma narsani talon-taroj qilishni va yoqishni biladilar. Ushbu jinoyatlar muammolardan muammolarga qadar o\'sishdan oldin ularni to\'xtatish kerak.',
    2: 'General, ork to\'dasi bizning eng katta muammoimiz emas edi! Janubiy Port aholisi taqiqlangan erlardan Black Mages tomonidan qilingan hujumlar haqida xabar berishdi. Siz va sizning batalyoningiz shahar xavfsizligini ta\'minlash uchun u erga yuborilgan. Omad tilaymiz, general!',
    3: 'Lineriya himoyachisi, biz qadimgi Hammerxold darvozasidamiz. Yaqinda Qora Mages, Orklar va Chayonlar qo\'shinlari qal\'a devorlarining so\'nggi himoyachilarini yo\'q qiladi. Do\'stlaringizga kirish va yordam qo\'lini cho\'zish vaqti keldi!',
  },
  enemy: {
    littleOrc: 'kichik ork',
    wizardBlack: 'qora sehrgar',
    scorpio: 'chayon'
  },
  tower: {
    archers: 'KAMONCHILAR MINORASI',
    artillery: 'ARTILLERYA MINORASI',
    magic: 'SEHRGAR MINORASI'
  }
}
